### ISSUE TITLE
Clicking on the notification if the app is running causes the app to crash

### ISSUE THREAD

**Issue by EiTaNBaRiBoA** [kyoz/godot-local-notification#2]
### Godot version

4.1.3

### Plugin version

1.0.1

### Phone information

Xiaomi Poco F5

### Issue description

When running the app and clicking on the notification, it relaunches the app and cause the app to crash.

### Steps to reproduce

1. Create a button in the scene.
2. Add a script to the button
```GDscript
func _ready():
	LocalNotification.init()
	LocalNotification.requestPermission()
	await LocalNotification.on_permission_request_completed
	


func _on_button_down():
	if LocalNotification.isPermissionGranted():
		LocalNotification.show("title","message",1,2)
```
3. export the app on the phone as aab and click on the button.
4. click on the notification and the app relaunches and crashes

**Comment by kyoz** [comment]
Hello @EiTaNBaRiBoA Ei, what í your phone android version?

**Comment by EiTaNBaRiBoA** [comment]
> Hello @EiTaNBaRiBoA Ei, what í your phone android version?

Android 13, Miui 14.0.7

**Comment by kyoz** [comment]
@EiTaNBaRiBoA Confirmed. By normally clicking on the notification will open the app. But because the app is already open, it will reload the app instead. On MiUI it may crash as you said. I'll find a way to fix it.

ref:
https://stackoverflow.com/questions/72166094/how-to-prevent-pendingintent-from-creating-a-new-activity-in-android
https://github.com/godotengine/godot/issues/83924

**Comment by kyoz** [comment]
Hello @EiTaNBaRiBoA, i've tried to fix it, it now work properly on my phones, but unluckily i'm not own any Xiaomi's phones.

Can you help me test it.

Below are production build for 4.1+ version. Please help me test it, if everything when well i'll release for all versions.

[android-template-4.1.zip](https://github.com/kyoz/godot-local-notification/files/13465997/android-template-4.1.zip)

**Comment by EiTaNBaRiBoA** [comment]
It is still happening, i attached a video. As you see i clicked on a button that changes the sky to night and i receive a notification, after i click it , it relaunches the app

https://github.com/kyoz/godot-local-notification/assets/62957978/7c41d53f-e799-4bae-93c3-18aa3cf48b90

**Comment by kyoz** [comment]
https://github.com/kyoz/godot-local-notification/assets/29815830/fad7e559-8167-48d2-850f-1c30e8c56066

Hmm. That's odd, i'll try to debug it more. There are 4.1.3 version build, can you try it again, please make sure you delete the old plugin, copy the new one, toggle the notification plugin again.

[android-template-4.1.3.zip](https://github.com/kyoz/godot-local-notification/files/13466008/android-template-4.1.3.zip)

**Comment by EiTaNBaRiBoA** [comment]
I deleted the plugin and reimported. i also deleted the data in the app and opened it again. Can you send me this test project to see if it not a project related because i found this https://stackoverflow.com/questions/58794910/fcm-notification-crashes-miui-on-foreground-android

https://github.com/kyoz/godot-local-notification/assets/62957978/573c2757-ca6b-44d2-9f6e-0cc936e22e89

**Comment by kyoz** [comment]
You have to delete the app, and build/run a new one for the new plugin to attack to your app. Here is a test app:

https://drive.google.com/file/d/1DJFSsZePaSLomJL7CK2k1aTCm8q8Phc1/view?usp=sharing

**Comment by EiTaNBaRiBoA** [comment]
Yours works, and also tested as you told me to delete the app and build/run a new one and it still happening in my project. weird, is it ok to ask if you can send me the source of this test project to compare what are the differences?

**Comment by kyoz** [comment]
[example.zip](https://github.com/kyoz/godot-local-notification/files/13466045/example.zip)

Here is it. You have to install android build template and copy the plugin yourself cause if i send everything i'll be 1.5GB.

Also, all of my Godot plugins have example for testing and learn how to use the plugin, they are [here](https://github.com/kyoz/godot-local-notification/tree/main/example)

I don't think it's project diff, i think it's by caching problem.

**Comment by EiTaNBaRiBoA** [comment]
> [example.zip](https://github.com/kyoz/godot-local-notification/files/13466045/example.zip)
> 
> Here is it. You have to install android build template and copy the plugin yourself cause if i send everything i'll be 1.5GB.
> 
> Also, all of my Godot plugins have example for testing and learn how to use the plugin, they are [here](https://github.com/kyoz/godot-local-notification/tree/main/example)
> 
> I don't think it's project diff, i think it's by caching problem.

Awesome thanks, I will take a look at the caching issue and also do more testing to see if it also could be godot androidmanifest.xml related from the stackoverflow i sent because someone had the same issue.

**Comment by kyoz** [comment]
Sure, i'll testing it more myself too, to ensure it work properly before i build and release new version.
