### ISSUE TITLE
Invalid plugin config file MyStaticlib.gdip while exporting ios project from Godot

### ISSUE THREAD

**Issue by kyadalu1** [kyoz/godot-local-notification#4]
### Godot version

4.2

### Plugin version

v1.0.0

### Phone information

Iphone 11 ios 15

### Issue description

This is not an issue with your Plugin. I just needed your attention on an issue i am facing. I am currently learning how to create an iOS plugin for myself, I tried going through your repo but it seems extremely complicated for me and i am not sure where to even start. Sorry to raise this as an issue, if you find this annoying you can close the issue.

### Steps to reproduce

I am trying to learn how to create iOS plugin for Godot engine. I just created simple iOS plugin which stores some key value data in UserDefaults and retrieve it. Here are the steps which i followed

Download Godot source code from master branch
`brew install scons`
cd to Godot source code directory in terminal and ran `scons platform=ios target=template_release -j4 `
Open xcode and selected static library for iOS
Go to the downloaded godot-repo, navigate to platform / iOS folder and add this path to Build settings => Header Search Paths in Xcode
Add the required code to my objective-c file & selected my iOS simulator and ran Command + B for the library to be build which is successfull
Create my Godot poject in Godot editor and created a bin folder
Found the libmystatticlib.a from my iOS project and copy pasted it to the bin folder of my iOS project
Create a folder called iOS and inside that a plugins folder. In pulgins folder created .gdip file and copied the code from [docs](https://docs.godotengine.org/en/stable/tutorials/platform/ios/ios_plugin.html#creating-an-ios-plugin) and refactored it according to my needs
In Godot, click project => Export => Add iOS => Click Fix Import Error => Added bundle identifier & App Store team id
Created a button in Godot tscn and added pressed listener to gdscript file
On button pressed code , added the followed code

```
var bridge = load("res://ios/plugins/MyStaticlib.gdip").new()
bridge._save_value("Hello", "keyhello")
```

### Additional context

When i try to export my godot project for iOS i keep getting error saying Invalid plugin config file MyStaticlib.gdip

Which step am i doing wrong. Please help

[Here](https://github.com/kyadalu1/IosSamplePlugin) is the sample ios plugin repo
[Here](https://github.com/kyadalu1/GodotSampleApp) is the sample godot projectn repo

**Comment by kyoz** [comment]
It may have something wrong with your `.gdip` file, It has to have correct release plugin name file and the plugin's name it self correct. or else Godot will unable to find and register your plugin.

Here is an example:

```
[config]
name="Local Notification"
binary="local-notification.a"

initialization="register_local_notification_types"
deinitialization="unregister_local_notification_types"

[dependencies]
linked=[]
embedded=[]
system=[]

capabilities=[]

files=[]

[plist]
```

Make sure these are correct in your plugin scripts:

```
binary="local-notification.a"

initialization="register_local_notification_types"
deinitialization="unregister_local_notification_types"
```

The plugin file name must be correct, so the initialization and deinitialization name.

Here is a full detail of [godot plugin guide](https://docs.godotengine.org/en/stable/tutorials/platform/ios/ios_plugin.html)

Please check em again and the try to build. Let me know if it still doesn't work, i'll try to debug and help.

**Comment by kyadalu1** [comment]
Thank you so much for your reply

Just to narrow down the scope of the error, here is what i did. I am no good in `objective-c` or `C++` so i cloned your flashlight iOS plugin. Then i opened the project in `Xcode` and added the required headers of Godot engine v4.2 to `Xcode` by navigating to `Build settings` =>  `Header search path`

Then i build my project for iOS simulator. I found the `libflashlight.a` file and created a Godot project and added iOS template.

Next in my Godot project i created iOS folder, inside that created plugins folder and copy pasted the `libflashlight.a` and copy pasted the `.gdip` file which you had for your flashlight ios plugin


Firstly i am not able to see my plugin when i navigate to Project => Project Settings => Plugins in my Godot Project


Also when i try to export my project i get error saying 

`Invalid plugin config file flashlight.gdip`


Here is the flashlight.gdip file

```
[config]
name="Flashlight"
binary="flashlight.a"

initialization="register_flashlight_types"
deinitialization="unregister_flashlight_types"

[dependencies]
linked=[]
embedded=[]
system=[]

capabilities=[]

files=[]

[plist]


```

**Comment by kyadalu1** [comment]
Thanks man i was able to resolve the issue. You were correct there was naming issue in my `.gdip` file

But i am still not able to see my plugin when i navigate to Project => Project Settings => Plugins in my Godot Project

**Comment by kyadalu1** [comment]
Ok Got it => For iOS it is in Project => Export. Thanks a lot for your help. God bless you
